name: CICD By DevOps Shack

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/*.jar

      # --- Trivy FS scan ---
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sudo sh -s -- -b /usr/local/bin

      - name: Trivy FS Scan
        run: trivy fs --format table -o trivy-fs-report.html .

      - name: Upload Trivy FS report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.html

      # --- Docker build & scan ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t maestrodomb/boardgame:latest .

      - name: Trivy Image Scan
        run: trivy image --format table -o trivy-image-report.html maestrodomb/boardgame:latest

      - name: Upload Trivy Image report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.html

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push maestrodomb/boardgame:latest

      # --- Deploy ---
      - name: Kubectl Action
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Apply manifests
        run: |
          kubectl apply -f deployment-service.yaml -n webapps
          kubectl get svc -n webapps
